package com.hospital.hospital.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class DrugDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public DrugDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSerialNumIsNull() {
            addCriterion("serial_num is null");
            return (Criteria) this;
        }

        public Criteria andSerialNumIsNotNull() {
            addCriterion("serial_num is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNumEqualTo(String value) {
            addCriterion("serial_num =", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotEqualTo(String value) {
            addCriterion("serial_num <>", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumGreaterThan(String value) {
            addCriterion("serial_num >", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumGreaterThanOrEqualTo(String value) {
            addCriterion("serial_num >=", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLessThan(String value) {
            addCriterion("serial_num <", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLessThanOrEqualTo(String value) {
            addCriterion("serial_num <=", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumLike(String value) {
            addCriterion("serial_num like", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotLike(String value) {
            addCriterion("serial_num not like", value, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumIn(List<String> values) {
            addCriterion("serial_num in", values, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotIn(List<String> values) {
            addCriterion("serial_num not in", values, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumBetween(String value1, String value2) {
            addCriterion("serial_num between", value1, value2, "serialNum");
            return (Criteria) this;
        }

        public Criteria andSerialNumNotBetween(String value1, String value2) {
            addCriterion("serial_num not between", value1, value2, "serialNum");
            return (Criteria) this;
        }

        public Criteria andGenericNameIsNull() {
            addCriterion("Generic_name is null");
            return (Criteria) this;
        }

        public Criteria andGenericNameIsNotNull() {
            addCriterion("Generic_name is not null");
            return (Criteria) this;
        }

        public Criteria andGenericNameEqualTo(String value) {
            addCriterion("Generic_name =", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameNotEqualTo(String value) {
            addCriterion("Generic_name <>", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameGreaterThan(String value) {
            addCriterion("Generic_name >", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameGreaterThanOrEqualTo(String value) {
            addCriterion("Generic_name >=", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameLessThan(String value) {
            addCriterion("Generic_name <", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameLessThanOrEqualTo(String value) {
            addCriterion("Generic_name <=", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameLike(String value) {
            addCriterion("Generic_name like", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameNotLike(String value) {
            addCriterion("Generic_name not like", value, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameIn(List<String> values) {
            addCriterion("Generic_name in", values, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameNotIn(List<String> values) {
            addCriterion("Generic_name not in", values, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameBetween(String value1, String value2) {
            addCriterion("Generic_name between", value1, value2, "genericName");
            return (Criteria) this;
        }

        public Criteria andGenericNameNotBetween(String value1, String value2) {
            addCriterion("Generic_name not between", value1, value2, "genericName");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeIsNull() {
            addCriterion("Freight_yard_code is null");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeIsNotNull() {
            addCriterion("Freight_yard_code is not null");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeEqualTo(String value) {
            addCriterion("Freight_yard_code =", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeNotEqualTo(String value) {
            addCriterion("Freight_yard_code <>", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeGreaterThan(String value) {
            addCriterion("Freight_yard_code >", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Freight_yard_code >=", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeLessThan(String value) {
            addCriterion("Freight_yard_code <", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeLessThanOrEqualTo(String value) {
            addCriterion("Freight_yard_code <=", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeLike(String value) {
            addCriterion("Freight_yard_code like", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeNotLike(String value) {
            addCriterion("Freight_yard_code not like", value, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeIn(List<String> values) {
            addCriterion("Freight_yard_code in", values, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeNotIn(List<String> values) {
            addCriterion("Freight_yard_code not in", values, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeBetween(String value1, String value2) {
            addCriterion("Freight_yard_code between", value1, value2, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andFreightYardCodeNotBetween(String value1, String value2) {
            addCriterion("Freight_yard_code not between", value1, value2, "freightYardCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNull() {
            addCriterion("bar_code is null");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNotNull() {
            addCriterion("bar_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarCodeEqualTo(String value) {
            addCriterion("bar_code =", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotEqualTo(String value) {
            addCriterion("bar_code <>", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThan(String value) {
            addCriterion("bar_code >", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bar_code >=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThan(String value) {
            addCriterion("bar_code <", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThanOrEqualTo(String value) {
            addCriterion("bar_code <=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLike(String value) {
            addCriterion("bar_code like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotLike(String value) {
            addCriterion("bar_code not like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIn(List<String> values) {
            addCriterion("bar_code in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotIn(List<String> values) {
            addCriterion("bar_code not in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeBetween(String value1, String value2) {
            addCriterion("bar_code between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotBetween(String value1, String value2) {
            addCriterion("bar_code not between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andDosageFormIsNull() {
            addCriterion("Dosage_form is null");
            return (Criteria) this;
        }

        public Criteria andDosageFormIsNotNull() {
            addCriterion("Dosage_form is not null");
            return (Criteria) this;
        }

        public Criteria andDosageFormEqualTo(String value) {
            addCriterion("Dosage_form =", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormNotEqualTo(String value) {
            addCriterion("Dosage_form <>", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormGreaterThan(String value) {
            addCriterion("Dosage_form >", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormGreaterThanOrEqualTo(String value) {
            addCriterion("Dosage_form >=", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormLessThan(String value) {
            addCriterion("Dosage_form <", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormLessThanOrEqualTo(String value) {
            addCriterion("Dosage_form <=", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormLike(String value) {
            addCriterion("Dosage_form like", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormNotLike(String value) {
            addCriterion("Dosage_form not like", value, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormIn(List<String> values) {
            addCriterion("Dosage_form in", values, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormNotIn(List<String> values) {
            addCriterion("Dosage_form not in", values, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormBetween(String value1, String value2) {
            addCriterion("Dosage_form between", value1, value2, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andDosageFormNotBetween(String value1, String value2) {
            addCriterion("Dosage_form not between", value1, value2, "dosageForm");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIsNull() {
            addCriterion("Invoice_type is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIsNotNull() {
            addCriterion("Invoice_type is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeEqualTo(String value) {
            addCriterion("Invoice_type =", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotEqualTo(String value) {
            addCriterion("Invoice_type <>", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeGreaterThan(String value) {
            addCriterion("Invoice_type >", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Invoice_type >=", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeLessThan(String value) {
            addCriterion("Invoice_type <", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeLessThanOrEqualTo(String value) {
            addCriterion("Invoice_type <=", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeLike(String value) {
            addCriterion("Invoice_type like", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotLike(String value) {
            addCriterion("Invoice_type not like", value, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeIn(List<String> values) {
            addCriterion("Invoice_type in", values, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotIn(List<String> values) {
            addCriterion("Invoice_type not in", values, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeBetween(String value1, String value2) {
            addCriterion("Invoice_type between", value1, value2, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andInvoiceTypeNotBetween(String value1, String value2) {
            addCriterion("Invoice_type not between", value1, value2, "invoiceType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeIsNull() {
            addCriterion("Medication_type is null");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeIsNotNull() {
            addCriterion("Medication_type is not null");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeEqualTo(String value) {
            addCriterion("Medication_type =", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeNotEqualTo(String value) {
            addCriterion("Medication_type <>", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeGreaterThan(String value) {
            addCriterion("Medication_type >", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Medication_type >=", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeLessThan(String value) {
            addCriterion("Medication_type <", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeLessThanOrEqualTo(String value) {
            addCriterion("Medication_type <=", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeLike(String value) {
            addCriterion("Medication_type like", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeNotLike(String value) {
            addCriterion("Medication_type not like", value, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeIn(List<String> values) {
            addCriterion("Medication_type in", values, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeNotIn(List<String> values) {
            addCriterion("Medication_type not in", values, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeBetween(String value1, String value2) {
            addCriterion("Medication_type between", value1, value2, "medicationType");
            return (Criteria) this;
        }

        public Criteria andMedicationTypeNotBetween(String value1, String value2) {
            addCriterion("Medication_type not between", value1, value2, "medicationType");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberIsNull() {
            addCriterion("Approval_number is null");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberIsNotNull() {
            addCriterion("Approval_number is not null");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberEqualTo(String value) {
            addCriterion("Approval_number =", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberNotEqualTo(String value) {
            addCriterion("Approval_number <>", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberGreaterThan(String value) {
            addCriterion("Approval_number >", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Approval_number >=", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberLessThan(String value) {
            addCriterion("Approval_number <", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberLessThanOrEqualTo(String value) {
            addCriterion("Approval_number <=", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberLike(String value) {
            addCriterion("Approval_number like", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberNotLike(String value) {
            addCriterion("Approval_number not like", value, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberIn(List<String> values) {
            addCriterion("Approval_number in", values, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberNotIn(List<String> values) {
            addCriterion("Approval_number not in", values, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberBetween(String value1, String value2) {
            addCriterion("Approval_number between", value1, value2, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andApprovalNumberNotBetween(String value1, String value2) {
            addCriterion("Approval_number not between", value1, value2, "approvalNumber");
            return (Criteria) this;
        }

        public Criteria andFactoryIsNull() {
            addCriterion("factory is null");
            return (Criteria) this;
        }

        public Criteria andFactoryIsNotNull() {
            addCriterion("factory is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryEqualTo(String value) {
            addCriterion("factory =", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotEqualTo(String value) {
            addCriterion("factory <>", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryGreaterThan(String value) {
            addCriterion("factory >", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryGreaterThanOrEqualTo(String value) {
            addCriterion("factory >=", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLessThan(String value) {
            addCriterion("factory <", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLessThanOrEqualTo(String value) {
            addCriterion("factory <=", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLike(String value) {
            addCriterion("factory like", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotLike(String value) {
            addCriterion("factory not like", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryIn(List<String> values) {
            addCriterion("factory in", values, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotIn(List<String> values) {
            addCriterion("factory not in", values, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryBetween(String value1, String value2) {
            addCriterion("factory between", value1, value2, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotBetween(String value1, String value2) {
            addCriterion("factory not between", value1, value2, "factory");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsIsNull() {
            addCriterion("National_essential_drugs is null");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsIsNotNull() {
            addCriterion("National_essential_drugs is not null");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsEqualTo(Boolean value) {
            addCriterion("National_essential_drugs =", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsNotEqualTo(Boolean value) {
            addCriterion("National_essential_drugs <>", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsGreaterThan(Boolean value) {
            addCriterion("National_essential_drugs >", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("National_essential_drugs >=", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsLessThan(Boolean value) {
            addCriterion("National_essential_drugs <", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsLessThanOrEqualTo(Boolean value) {
            addCriterion("National_essential_drugs <=", value, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsIn(List<Boolean> values) {
            addCriterion("National_essential_drugs in", values, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsNotIn(List<Boolean> values) {
            addCriterion("National_essential_drugs not in", values, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsBetween(Boolean value1, Boolean value2) {
            addCriterion("National_essential_drugs between", value1, value2, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andNationalEssentialDrugsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("National_essential_drugs not between", value1, value2, "nationalEssentialDrugs");
            return (Criteria) this;
        }

        public Criteria andDrugUsageIsNull() {
            addCriterion("Drug_usage is null");
            return (Criteria) this;
        }

        public Criteria andDrugUsageIsNotNull() {
            addCriterion("Drug_usage is not null");
            return (Criteria) this;
        }

        public Criteria andDrugUsageEqualTo(String value) {
            addCriterion("Drug_usage =", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageNotEqualTo(String value) {
            addCriterion("Drug_usage <>", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageGreaterThan(String value) {
            addCriterion("Drug_usage >", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageGreaterThanOrEqualTo(String value) {
            addCriterion("Drug_usage >=", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageLessThan(String value) {
            addCriterion("Drug_usage <", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageLessThanOrEqualTo(String value) {
            addCriterion("Drug_usage <=", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageLike(String value) {
            addCriterion("Drug_usage like", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageNotLike(String value) {
            addCriterion("Drug_usage not like", value, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageIn(List<String> values) {
            addCriterion("Drug_usage in", values, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageNotIn(List<String> values) {
            addCriterion("Drug_usage not in", values, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageBetween(String value1, String value2) {
            addCriterion("Drug_usage between", value1, value2, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andDrugUsageNotBetween(String value1, String value2) {
            addCriterion("Drug_usage not between", value1, value2, "drugUsage");
            return (Criteria) this;
        }

        public Criteria andSingleDoseIsNull() {
            addCriterion("Single_dose is null");
            return (Criteria) this;
        }

        public Criteria andSingleDoseIsNotNull() {
            addCriterion("Single_dose is not null");
            return (Criteria) this;
        }

        public Criteria andSingleDoseEqualTo(String value) {
            addCriterion("Single_dose =", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseNotEqualTo(String value) {
            addCriterion("Single_dose <>", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseGreaterThan(String value) {
            addCriterion("Single_dose >", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseGreaterThanOrEqualTo(String value) {
            addCriterion("Single_dose >=", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseLessThan(String value) {
            addCriterion("Single_dose <", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseLessThanOrEqualTo(String value) {
            addCriterion("Single_dose <=", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseLike(String value) {
            addCriterion("Single_dose like", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseNotLike(String value) {
            addCriterion("Single_dose not like", value, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseIn(List<String> values) {
            addCriterion("Single_dose in", values, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseNotIn(List<String> values) {
            addCriterion("Single_dose not in", values, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseBetween(String value1, String value2) {
            addCriterion("Single_dose between", value1, value2, "singleDose");
            return (Criteria) this;
        }

        public Criteria andSingleDoseNotBetween(String value1, String value2) {
            addCriterion("Single_dose not between", value1, value2, "singleDose");
            return (Criteria) this;
        }

        public Criteria andDayIsNull() {
            addCriterion("day is null");
            return (Criteria) this;
        }

        public Criteria andDayIsNotNull() {
            addCriterion("day is not null");
            return (Criteria) this;
        }

        public Criteria andDayEqualTo(Integer value) {
            addCriterion("day =", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotEqualTo(Integer value) {
            addCriterion("day <>", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThan(Integer value) {
            addCriterion("day >", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("day >=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThan(Integer value) {
            addCriterion("day <", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayLessThanOrEqualTo(Integer value) {
            addCriterion("day <=", value, "day");
            return (Criteria) this;
        }

        public Criteria andDayIn(List<Integer> values) {
            addCriterion("day in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotIn(List<Integer> values) {
            addCriterion("day not in", values, "day");
            return (Criteria) this;
        }

        public Criteria andDayBetween(Integer value1, Integer value2) {
            addCriterion("day between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andDayNotBetween(Integer value1, Integer value2) {
            addCriterion("day not between", value1, value2, "day");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNull() {
            addCriterion("Frequency is null");
            return (Criteria) this;
        }

        public Criteria andFrequencyIsNotNull() {
            addCriterion("Frequency is not null");
            return (Criteria) this;
        }

        public Criteria andFrequencyEqualTo(String value) {
            addCriterion("Frequency =", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotEqualTo(String value) {
            addCriterion("Frequency <>", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThan(String value) {
            addCriterion("Frequency >", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyGreaterThanOrEqualTo(String value) {
            addCriterion("Frequency >=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThan(String value) {
            addCriterion("Frequency <", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLessThanOrEqualTo(String value) {
            addCriterion("Frequency <=", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyLike(String value) {
            addCriterion("Frequency like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotLike(String value) {
            addCriterion("Frequency not like", value, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyIn(List<String> values) {
            addCriterion("Frequency in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotIn(List<String> values) {
            addCriterion("Frequency not in", values, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyBetween(String value1, String value2) {
            addCriterion("Frequency between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andFrequencyNotBetween(String value1, String value2) {
            addCriterion("Frequency not between", value1, value2, "frequency");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(String value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(String value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(String value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(String value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(String value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(String value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLike(String value) {
            addCriterion("total like", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotLike(String value) {
            addCriterion("total not like", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<String> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<String> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(String value1, String value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(String value1, String value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andDrugExplainIsNull() {
            addCriterion("Drug_Explain is null");
            return (Criteria) this;
        }

        public Criteria andDrugExplainIsNotNull() {
            addCriterion("Drug_Explain is not null");
            return (Criteria) this;
        }

        public Criteria andDrugExplainEqualTo(String value) {
            addCriterion("Drug_Explain =", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainNotEqualTo(String value) {
            addCriterion("Drug_Explain <>", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainGreaterThan(String value) {
            addCriterion("Drug_Explain >", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainGreaterThanOrEqualTo(String value) {
            addCriterion("Drug_Explain >=", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainLessThan(String value) {
            addCriterion("Drug_Explain <", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainLessThanOrEqualTo(String value) {
            addCriterion("Drug_Explain <=", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainLike(String value) {
            addCriterion("Drug_Explain like", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainNotLike(String value) {
            addCriterion("Drug_Explain not like", value, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainIn(List<String> values) {
            addCriterion("Drug_Explain in", values, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainNotIn(List<String> values) {
            addCriterion("Drug_Explain not in", values, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainBetween(String value1, String value2) {
            addCriterion("Drug_Explain between", value1, value2, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andDrugExplainNotBetween(String value1, String value2) {
            addCriterion("Drug_Explain not between", value1, value2, "drugExplain");
            return (Criteria) this;
        }

        public Criteria andEffectIsNull() {
            addCriterion("Effect is null");
            return (Criteria) this;
        }

        public Criteria andEffectIsNotNull() {
            addCriterion("Effect is not null");
            return (Criteria) this;
        }

        public Criteria andEffectEqualTo(String value) {
            addCriterion("Effect =", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotEqualTo(String value) {
            addCriterion("Effect <>", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectGreaterThan(String value) {
            addCriterion("Effect >", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectGreaterThanOrEqualTo(String value) {
            addCriterion("Effect >=", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectLessThan(String value) {
            addCriterion("Effect <", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectLessThanOrEqualTo(String value) {
            addCriterion("Effect <=", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectLike(String value) {
            addCriterion("Effect like", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotLike(String value) {
            addCriterion("Effect not like", value, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectIn(List<String> values) {
            addCriterion("Effect in", values, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotIn(List<String> values) {
            addCriterion("Effect not in", values, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectBetween(String value1, String value2) {
            addCriterion("Effect between", value1, value2, "effect");
            return (Criteria) this;
        }

        public Criteria andEffectNotBetween(String value1, String value2) {
            addCriterion("Effect not between", value1, value2, "effect");
            return (Criteria) this;
        }

        public Criteria andSideEffectsIsNull() {
            addCriterion("Side_effects is null");
            return (Criteria) this;
        }

        public Criteria andSideEffectsIsNotNull() {
            addCriterion("Side_effects is not null");
            return (Criteria) this;
        }

        public Criteria andSideEffectsEqualTo(String value) {
            addCriterion("Side_effects =", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsNotEqualTo(String value) {
            addCriterion("Side_effects <>", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsGreaterThan(String value) {
            addCriterion("Side_effects >", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsGreaterThanOrEqualTo(String value) {
            addCriterion("Side_effects >=", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsLessThan(String value) {
            addCriterion("Side_effects <", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsLessThanOrEqualTo(String value) {
            addCriterion("Side_effects <=", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsLike(String value) {
            addCriterion("Side_effects like", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsNotLike(String value) {
            addCriterion("Side_effects not like", value, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsIn(List<String> values) {
            addCriterion("Side_effects in", values, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsNotIn(List<String> values) {
            addCriterion("Side_effects not in", values, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsBetween(String value1, String value2) {
            addCriterion("Side_effects between", value1, value2, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andSideEffectsNotBetween(String value1, String value2) {
            addCriterion("Side_effects not between", value1, value2, "sideEffects");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseIsNull() {
            addCriterion("Applicable_disease is null");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseIsNotNull() {
            addCriterion("Applicable_disease is not null");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseEqualTo(String value) {
            addCriterion("Applicable_disease =", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseNotEqualTo(String value) {
            addCriterion("Applicable_disease <>", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseGreaterThan(String value) {
            addCriterion("Applicable_disease >", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseGreaterThanOrEqualTo(String value) {
            addCriterion("Applicable_disease >=", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseLessThan(String value) {
            addCriterion("Applicable_disease <", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseLessThanOrEqualTo(String value) {
            addCriterion("Applicable_disease <=", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseLike(String value) {
            addCriterion("Applicable_disease like", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseNotLike(String value) {
            addCriterion("Applicable_disease not like", value, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseIn(List<String> values) {
            addCriterion("Applicable_disease in", values, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseNotIn(List<String> values) {
            addCriterion("Applicable_disease not in", values, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseBetween(String value1, String value2) {
            addCriterion("Applicable_disease between", value1, value2, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andApplicableDiseaseNotBetween(String value1, String value2) {
            addCriterion("Applicable_disease not between", value1, value2, "applicableDisease");
            return (Criteria) this;
        }

        public Criteria andProductionDateIsNull() {
            addCriterion("production_Date is null");
            return (Criteria) this;
        }

        public Criteria andProductionDateIsNotNull() {
            addCriterion("production_Date is not null");
            return (Criteria) this;
        }

        public Criteria andProductionDateEqualTo(Date value) {
            addCriterionForJDBCDate("production_Date =", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("production_Date <>", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateGreaterThan(Date value) {
            addCriterionForJDBCDate("production_Date >", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("production_Date >=", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateLessThan(Date value) {
            addCriterionForJDBCDate("production_Date <", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("production_Date <=", value, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateIn(List<Date> values) {
            addCriterionForJDBCDate("production_Date in", values, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("production_Date not in", values, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("production_Date between", value1, value2, "productionDate");
            return (Criteria) this;
        }

        public Criteria andProductionDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("production_Date not between", value1, value2, "productionDate");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodIsNull() {
            addCriterion("Validity_period is null");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodIsNotNull() {
            addCriterion("Validity_period is not null");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodEqualTo(Integer value) {
            addCriterion("Validity_period =", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodNotEqualTo(Integer value) {
            addCriterion("Validity_period <>", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodGreaterThan(Integer value) {
            addCriterion("Validity_period >", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("Validity_period >=", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodLessThan(Integer value) {
            addCriterion("Validity_period <", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("Validity_period <=", value, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodIn(List<Integer> values) {
            addCriterion("Validity_period in", values, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodNotIn(List<Integer> values) {
            addCriterion("Validity_period not in", values, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodBetween(Integer value1, Integer value2) {
            addCriterion("Validity_period between", value1, value2, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andValidityPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("Validity_period not between", value1, value2, "validityPeriod");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(Double value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(Double value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(Double value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(Double value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(Double value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<Double> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<Double> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(Double value1, Double value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(Double value1, Double value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return (Criteria) this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEqualTo(String value) {
            addCriterion("other =", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotEqualTo(String value) {
            addCriterion("other <>", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThan(String value) {
            addCriterion("other >", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(String value) {
            addCriterion("other >=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThan(String value) {
            addCriterion("other <", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThanOrEqualTo(String value) {
            addCriterion("other <=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLike(String value) {
            addCriterion("other like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotLike(String value) {
            addCriterion("other not like", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherIn(List<String> values) {
            addCriterion("other in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotIn(List<String> values) {
            addCriterion("other not in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherBetween(String value1, String value2) {
            addCriterion("other between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotBetween(String value1, String value2) {
            addCriterion("other not between", value1, value2, "other");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_details
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 16 18:35:15 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}