package com.hospital.hospital.mapper;

import com.hospital.hospital.domain.AccessoryCost;
import com.hospital.hospital.domain.AccessoryCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccessoryCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int countByExample(AccessoryCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByExample(AccessoryCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insert(AccessoryCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insertSelective(AccessoryCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    List<AccessoryCost> selectByExample(AccessoryCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    AccessoryCost selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") AccessoryCost record, @Param("example") AccessoryCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExample(@Param("record") AccessoryCost record, @Param("example") AccessoryCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKeySelective(AccessoryCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accessory_cost
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKey(AccessoryCost record);
}