package com.hospital.hospital.mapper;

import com.hospital.hospital.domain.Disease;
import com.hospital.hospital.domain.DiseaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int countByExample(DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByExample(DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insert(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insertSelective(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    List<Disease> selectByExample(DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    Disease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Disease record, @Param("example") DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExample(@Param("record") Disease record, @Param("example") DiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKeySelective(Disease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKey(Disease record);
}