package com.hospital.hospital.mapper;

import com.hospital.hospital.domain.DrugDetails;
import com.hospital.hospital.domain.DrugDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrugDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int countByExample(DrugDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByExample(DrugDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insert(DrugDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insertSelective(DrugDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    List<DrugDetails> selectByExample(DrugDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    DrugDetails selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") DrugDetails record, @Param("example") DrugDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExample(@Param("record") DrugDetails record, @Param("example") DrugDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKeySelective(DrugDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_details
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKey(DrugDetails record);
}