package com.hospital.hospital.mapper;

import com.hospital.hospital.domain.MedicalRecord;
import com.hospital.hospital.domain.MedicalRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MedicalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table
     *medical_record
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int countByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByExample(MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insert(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insertSelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    List<MedicalRecord> selectByExample(MedicalRecordExample example);//查找所有存在数据

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    MedicalRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") MedicalRecord record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExample(@Param("record") MedicalRecord record, @Param("example") MedicalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKeySelective(MedicalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table medical_record
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKey(MedicalRecord record);

    void deletemdrcount(@Param("array") String[] idAmedicine_id);//通过id实现批量删除

}