package com.hospital.hospital.mapper;

import com.hospital.hospital.domain.Prescription;
import com.hospital.hospital.domain.PrescriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int countByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insert(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int insertSelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    List<Prescription> selectByExample(PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    Prescription selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") Prescription record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByExample(@Param("record") Prescription record, @Param("example") PrescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKeySelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated Wed Jan 16 18:35:15 CST 2019
     */
    int updateByPrimaryKey(Prescription record);
}